version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Approval check'
    validate:
      - do: approvals
        min:
          count: 1
        limit:
          teams: ['rancher/ui']
  - when: pull_request.*, pull_request_review.*, 'issues.*'
    name: 'Milestone check  '
    validate:
      - do: milestone
        no_empty:
          enabled: true
          message: 'Custom message...'