version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Approved by rancher/ui team member'
    validate:
      - do: approvals
        min:
          count: 1
        limit:
          teams: ['richard-cox-org/richard-cox-team']
  - when: pull_request.*, pull_request_review.*
    name: 'Has a milestone'
    validate:
      - do: milestone
        no_empty:
          enabled: true