name: Publish Docusaurus

on:
  push:
    branches:
      - master
      # TODO RC remove
      - gh-action-remove-peaceiris
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn

      - name: Install dependencies
        run: cd docusaurus/ && yarn install:ci
      - name: Build website
        run: cd docusaurus/ && yarn build
      - name: Add CNAME
        run: |
          echo "extensions.rancher.io" > ./docusaurus/build/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docusaurus/build

  # Seperate the deploy job to isolate write permissions
  deploy:
    name: Publish Docusaurus
    # TODO RC `rancher`
    if: ${{ github.event_name == 'push' && github.repository_owner == 'richard-cox' }}
    runs-on: ubuntu-latest
    needs: build

    # This is required to avoid https://github.com/actions/deploy-pages/issues/271
    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4