name: gh-project-integration
on:
  pull_request_target:
    types: [ opened, reopened, edited, closed ]

jobs:
  rancher_gh_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: script
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_PROJECT: ${{ secrets.PR_PROJECT }}
      run: node .github/workflows/scripts/pr-gh-project.js
